### PR TITLE
Adding buddy.hashers

### PR DESCRIPTION
**Pull request by judepayne**
One thing I wasn't quite sure of. In buddy.clj I added the hashers ns only under pod.babashka.buddy.hashers and not under pod.babashka.buddy.core.hashers as well (as seemed to be the case for existing nses). Hope I made the right choice!

### CODE REVIEW

**Comment by borkdude** [comment]
I think this looks good. Can you merge with main? I updated the build config to not cause the build to fail.

**Comment by borkdude** [comment]
I don't know why we have all those `.core` namespaces btw, maybe we could just remove them, but I suspect they are there for backwards compatibility. We can update the README to not show them anymore though.

**Comment by borkdude** [comment]
Why are you closing?

**Comment by judepayne** [comment]
Just in error. Re-opened!

**Comment by judepayne** [comment]
think that it is. merged into main on my fork. Been a while since I've done a PR! What do I need to do, or do you take it from here?

**Comment by borkdude** [comment]
Can you push your merged fork to this PR?

**Comment by judepayne** [comment]
Think that's it

**Comment by borkdude** [comment]
Yaay! :)

**Comment by borkdude** [comment]
Released

**Pull request merged**
